@startuml NaN Air
hide empty members

Package Main {
  Class Location {
    + id: number
    + country: string
    + city: string
    + airport: string
    + address: string
    + phone: number
    + openinghours: string
    + manager_id: number
  }
  Class Employee {
    + id: number
    + location_id: number
    + name: string
    + ssn: number
    + address: string
    + phone: number
    + mobile: number
    + email: string
    + role: Role
  }
  Class Contractor {
    + id: number
    + location_id: number
    + name: string
    + contact: string
    + phone: number
    + openinghours: string
    + email: string
    + speciality: string
  }
  Class Building {
    + id: number
    + registration: number
    + location_id: number
    + free: boolean
    + description: string
    + state: string
    + address: string
    + size: number
    + rooms: number
    + type: string
  }
  Class Accessory {
    + id: number
    + building_id: number
    + description: string
    + state: string
    + bought: Date
    + last_maintained: Date
  }

  Class Task {
    + id: number
    + loaction_id: number
    + building_id: number
    + employee_id: number
    + title: string
    + description: string
    + type: string
    + start_date: Date
    + due_date: Date
    + modified: Date
    + priority: Priority
    + recurring: Recurrance
    + repeats_every: string
    + state: TaskState
    + estimated_cost: number
  }
  Class Report {
    + id: number
    + report_date: Date
    + approved: boolean
    + description: string
    + type: TaskType
    + hours: number
    + note: string
  }
  Class EmployeeReport {
    + employee_id: number
    + task_id: number
    + material_cost: number
    + labor_cost: number
    + total_cost: number
  }
  Class ContractorReport {
    + contractor_id: number
    + employee_report_id: number
    + contractor_fee: number
    + contractor_grade: number
  }
  
 Class Menu {
    + menu_items

    + add_menu_item()
    + get_options()
    - getitem()
    - iter()
  }
  Class MenuItem {
    + name
    + option
    + connection
  }
  Class Form {
    + form_fields

    - getitem()
    - iter()
  }
  Class FormField {
    + key
    + name
    + value
    + lines
    + cols 
    + filter
    + editable
    + validators
    + options
    + border

    + get_lines()
    + set_position()
  }

  Class Table {
    + table_column

    + next_page()
    + previous_page()
    + first_page()
    + last_page()
    - pages_info()
    - add_columns()
    - getitem()
    - iter()
  }
  Class TableColumn {
    + name
    + rows
    + max_lines

    + get_width()

  }

  Form o-- FormField
  Menu o-- MenuItem
  Table o-- TableColumn

  Report <|-- EmployeeReport
  Report <|-- ContractorReport
  Task *-- EmployeeReport
  EmployeeReport o-- ContractorReport
  Employee -- EmployeeReport
  Location "1" -- "1..*" Employee
  Location "1" -- "1..*" Building
  Location "1" -- "*" Contractor
  Building -- Task
  Accessory o-- Task
  Contractor o-- ContractorReport
  Building *- Accessory
}

@enduml